server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: aston-project

  datasource:
    url: jdbc:postgresql://localhost:5432/aston_project_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: userEventDto:dev.gedfalk.astonproject.dto.UserEventDto
        spring.json.add.type.headers: true
    consumer:
      group-id: user-service-group

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html